/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package autonoma.demopelota.gui;

import autonoma.demopelota.elements.Campo;
import java.awt.Graphics;
import java.awt.Rectangle;
import java.awt.image.BufferedImage;
import javax.swing.Timer;

/**
 * 
 * @author Heily Yohana Rios Ayala <heilyy.riosa@autonoma.edu.co>
 * @since 20250524
 * @version 1.0.0
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private Campo campo;
    private BufferedImage buffer;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal(Campo campo) {
        initComponents();
        this.campo = campo;
         setSize(1200, 600);
        setLocationRelativeTo(null);
        setResizable(false);
        
           Timer timer = new Timer(50, e -> repaint());
         timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 

    public void setCampo(Campo campo) {
        this.campo = campo;
    }

        @Override
    public void paint(Graphics g) {
      if (buffer == null || buffer.getWidth() != getWidth() || buffer.getHeight() != getHeight()) {
        buffer = new BufferedImage(getWidth(), getHeight(), BufferedImage.TYPE_INT_ARGB);
        }

        Graphics g2 = buffer.getGraphics();
        
        g2.clearRect(0, 0, buffer.getWidth(), buffer.getHeight());

       
        if (campo!= null) {
            campo.paint(g2, getWidth(), getHeight());
        }

        g2.dispose();

       
        g.drawImage(buffer, 0, 0, null);
    }

    public void refresh() {
        this.repaint();
    }

    public Rectangle getBoundaries() {
        return this.getBounds();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
